// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fospaeebbvbezxjmyxxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZvc3BhZWViYnZiZXp4am15eHh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxMjk2NTcsImV4cCI6MjA3MjcwNTY1N30.cGh5EkW-dAyUbGBW9HtOD-4t61hpvwGQy0hYcq9PL3k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});